version: '3'
volumes:
  node_modules:
  postgres:
services:
  web:
    build: .
    image: bookist_web
    command: sh -c 'rm tmp/pids/server.pid; bundle exec rails s'
    environment:
      DATABASE_URL: postgres://bookist:bookist@db/bookist?sslmode=disable
      DATABASE_TEST_URL: postgres://bookist:bookist@db/bookist_test?sslmode=disable
      REDIS_URL: redis://redis:6379/1
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - node_modules:/app/node_modules
    links:
      - db
      - redis
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
  db:
    image: postgres:13.10
    environment:
      POSTGRES_USER: bookist
      POSTGRES_PASSWORD: bookist
      POSTGRES_DB: bookist
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'