default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://bookist:bookist@localhost:5432/bookist') %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV.fetch('DATABASE_TEST_URL', 'postgres://bookist:bookist@localhost:5432/bookist_test') %>

production:
  <<: *default
